### ISSUE TITLE
Stream Data from Oracle to Cassandra using Spark Streeming

### ISSUE THREAD

**Issue by nirmalb06** [doanduyhai/Cassandra-Spark-Demo#2]
Hi,

I have moved data from Oracle to Cassandra using spark, Now i want to Stream it to get those data as real time.

I just used a sample table in HR schema from oracle and moved the data to Cassandra table which has same structure. Now i want to Stream the date in real time to process the records and show it in reports. Please guide me in completing this live stream.

Thanks,
Nirmal.B

**Comment by doanduyhai** [comment]
This is a GitHub repo with sample codes, not a tutorial website. Ask your question on Stackoverflow or Google
